# Generated by Django 3.2.9 on 2021-11-22 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title_tag',
            new_name='location',
        ),
    ]
